[package]
name = "query-tests-setup"
version = "0.1.0"
authors = ["Dominic Petrick <dompetrick@gmail.com>"]
edition = "2018"

[dependencies]
serde_json = "1.0"
datamodel-connector = { path = "../../../libs/datamodel/connectors/datamodel-connector" }
mongodb-datamodel-connector = { path = "../../../libs/datamodel/connectors/mongodb-datamodel-connector" }
sql-datamodel-connector = { path = "../../../libs/datamodel/connectors/sql-datamodel-connector" }
prisma-models = { path = "../../../libs/prisma-models" }
lazy_static = "1.4"
enum_dispatch = "0.3"
migration-core = { path = "../../../migration-engine/core" }
request-handlers = { path = "../../request-handlers" }
tokio = "1.0"
query-core = { path = "../../core" }
datamodel = { path = "../../../libs/datamodel/core" }
feature-flags = { path = "../../../libs/feature-flags" }
thiserror = "1.0"
async-trait = "0.1"