[package]
name = "query-tests-setup"
version = "0.1.0"
authors = ["Dominic Petrick <dompetrick@gmail.com>"]
edition = "2018"

[dependencies]
serde_json = "1.0"
datamodel-connector = { path = "../../../libs/datamodel/connectors/datamodel-connector" }
mongodb-datamodel-connector = { path = "../../../libs/datamodel/connectors/mongodb-datamodel-connector" }
sql-datamodel-connector = { path = "../../../libs/datamodel/connectors/sql-datamodel-connector" }
