name: Query Engine
on:
  push:

jobs:

  test:
    name: "Test Query Engine - ${{ matrix.connector }}"
    
    strategy:
      fail-fast: false
      matrix:
        connector: [sqlite, postgresql9, postgresql10, postgresql11, postgresql12, postgresql13, pgbouncer, mysql, mysql56, mysql8, mariadb, mssql2017, mssql2019]
        
    container:
      image: prismagraphql/build:test
        
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: sbt test
        working-directory: query-engine/connector-test-kit
        env:
          SERVER_ROOT: /root/build
          TEST_CONNECTOR: ${{ matrix.connector }}
          TEST_MODE: simple
